# Generated by Django 4.1.4 on 2022-12-30 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmapp', '0002_alter_album_pub_date_alter_ordinaryuser_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='surname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(max_length=72, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 11, 49, 7, 242532), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 11, 49, 7, 243608), verbose_name='creation date'),
        ),
    ]
