# Generated by Django 4.1.4 on 2023-02-14 18:17

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wmapp', '0003_account_name_account_surname_alter_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='media'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 19, 15, 56, 471084), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 14, 19, 15, 56, 471084), verbose_name='creation date'),
        ),
    ]
