# Generated by Django 4.1.4 on 2023-02-25 20:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wmapp', '0005_alter_album_pub_date_alter_playlist_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 21, 7, 53, 696223), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 21, 7, 53, 701534), verbose_name='creation date'),
        ),
    ]
